backend:
  name: github
  repo: bewpot/sitoprova
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Testo", name: "body", widget: "markdown" }
